---
title: "Understanding Cannabis Usage in Canada: Consistent Demographic Patterns in Cannabis Use Across Canada May Positively Correlate to High Frequency Use"
subtitle: "An analysis of the 2021 Canadian Tobacco and Nicotine Survey (CTNS)"
author: "Emily Kim"
thanks: "Code and data are available at: https://github.com/emilykimto/CTNS-analysis.git"
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "The widespread use of tobacco, vaping, and cannabis in Canada has been an ongoing public health concern given their commonly associated negative health impacts including respiratory issues, impaired cognitive development, and addiction. To gain a deeper understanding of the factors driving usage rates for cannabis specifically, this paper aims to investigate the relationship between demographics such as gender and region, versus consumption method and frequency in Canada. By utilizing the data from Statistics Canada, we found that young adults and males are more likely to use cannabis products with higher usage rates in certain regions of Canada. The implications and possible solutions for addressing high usage rates are also discussed."
format: pdf
toc: TRUE
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false

```

# Introduction {#sec-introduction}

In 2018, the Canadian government led by Prime Minister Justin Trudeau, made the landmark decision to legalize the use of marijuana after a century of prohibition. While this move was praised as a step towards progressive drug policy by some, others expressed concerns about the potential negative effects on public health. Of particular concern was the potential increase in cannabis usage rates among the general population, especially young adults who would be at a higher long-term risk of negative health outcomes similar to those associated with tobacco, such respiratory issues, impaired cognitive development, and addiction.

In light of this recent legalization and the still ongoing research surrounding the effects of marijuana, I analyzed data from the 2021 Canadian Tobacco and Nicotine Survey (CTNS) obtained from Open Government Data of Statistics Canada to uncover the demographic that would be the most impacted by any negative health effects of cannabis products. To gain a more comprehensive understanding of what factors drive usage rates, I explore the estimand, how does user characteristics such as age, gender, and region correlate with cannabis consumption methods (smoking, vaping, taking edibles) and their respective frequencies of usage in Canada.

I will first discuss the source of our data, its biases, and review the CTNS sampling and key features. Then, I will create a model and discuss analysis results to identify the demographic patterns of cannabis usage in Canada, cannabis product type, and consumption frequency to discuss potential underlying user behaviour and motivations. Finally, I discuss the implications of the findings and possible solutions as to how public policy can better tackle the ongoing phenomenon of increasing substance use, as well as the weaknesses and future steps of this paper.

# Data and Methods {#sec-data}

## Data Management {#sec-first-point}
This paper utilizes the R statistical programming language [@citeR], along with packages tidyverse [@citetidyverse], here [@citehere], janitor [@citejanitor], and dplyr [@citedplyr]. The figures in this paper have been created using ggplot2 [@citeggplot2] and the tables have been created using knitr [@citeknitr] and kableExtra [@citekablextra]. The color styles in graphs have been created using the RColorBrewer packages [@citercolorbrewer].

## Source {#sec-second-point}
This paper uses data extracted from the Public Use Microdata File (PUMPF) for the 2021 Canadian Tobacco and Nicotine Survey (CTNS). The CTNS is a national survey conducted by Health Canada to collect information about the prevalence of cigarette smoking, vaping, and cannabis use in Canada. Until 2017, Statistics Canada administered the Canadian Tobacco, Alcohol and Drugs Survey (CTADS), which gathered information on the use of tobacco, alcohol, and drug use across Canada [@citectnspumf]. However, in 2019, the Canadian Alcohol and Drugs Survey (CADS) was carried out specifically to collect data on alcohol and drug use, separately from the Canadian Tobacco and Nicotine Survey (CTNS), which is focused mainly on gathering data on tobacco and nicotine use, including cannabis [@citectnspumf].

The PUMPF is a dataset that contains anonymized, individual-level data from the CTNS [@citectnspumf]. It is a subset of the full survey dataset that involves balancing the preservation of respondent confidentiality and providing the most useful data which is then made available to researchers and analysts who require access to detailed information on tobacco, nicotine, and cannabis use in Canada [@citectnspumf]. The CTNS PUMF includes information on a wide range of variables, including frequency of use, attitudes and beliefs, and use of cessation aids [@citectnspumf]. It also includes demographic variables such as age, gender, and province of residence [@citectnspumf].

Data collection for the 2022 reference period was conducted from December 1, 2020 to May 3, 2021, and was gathered directly and voluntarily from survey respondents either through an electronic questionnaire (EQ) or through CATI (computer- assisted telephone interviewing) [@citectnsinfo]. The 2021 CTNS electronic questionnaire was developed in consultation with Health Canada, and underwent a process of cognitive testing through in-depth interviews conducted by Statistics Canada's Questionnaire Design Resource Centre to test the survey content in both of Canada's official languages [@citectnsinfo].

## Sampling {#sec-third-point}
The CTNS is designed to provide a comprehensive picture of tobacco, nicotine, and cannabis use, attitudes, and behaviours among non-instituionalized Canadians ages 15 years and older who are not members of collectives or living on reserves [@citectnsinfo]. The survey has a stratified sample and cross-sectional design with sampling units: individuals aged 15 to 24 and individuals aged 25 and older [@citectnsinfo]. For the former (individuals aged 15 to 24), the CTNS sample has a one-stage desion, and the individual is the sampling unit [@citectnsinfo]. For the latter (individuals aged 25 and older), the CTNS sample has a two-stage design where the sampling unit for the first stage is the dwelling, and the sampling unit for the second stage is the individual [@citectnsinfo]. The CTNS used different methods for stratification. For those aged 15 to 24, the sample was stratified by age group and province, with a systematic sample selected independently for each group [@citectnsinfo]. For those aged 25 and older, the sample was stratified by province and a simple random sample of dwellings was selected [@citectnsinfo]. In terms of sampling and subsampling, the survey allocated samples to produce province-level and region-level estimates for the age groups. The initial sample size was 12,000 individuals aged 15-24 and 15,000 dwellings for those aged 25 and older [@citectnsinfo]. The survey sent an initial sample of 27,000 dwellings or individuals for collection [@citectnsinfo].

## Key Features {#sec-fourth-point}
This paper investigates the relationship between demographic factors and cannabis use in Canada. More specifically, it explores the estimand, how does characteristics such as user age, gender, and region correlate with cannabis consumption methods (smoking, vaping, taking edibles) and their respective frequencies of usage in Canada. In my analysis, I removed

(not right) -->2,164 responses to account for unanswered or not applicable responses. We did this to ensure that the data used in this paper is complete and representative of all variables. The variables we selected for our analysis can be seen in @tbl-1 and their measurement levels can be seen in @tbl-2. Responses were measured using Likert scales which measured respondents' opinions to the questions being asked.


## Bias and Ethics {#sec-fifth-point}

# Model {#sec-model}

# Results {#sec-results}

# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

The demographic patterns of cannabis usage across Canada.

Data - consider age (or) gender and region

## Second discussion point {#sec-second-point}

Data - cannabis product types and their consumption frequency.

Discuss potential underlying user behaviour and motivations.

Why do Canadians use cannabis?

## Weaknesses and Next Steps {#sec-weaknesses-and-next-steps}

Discuss implications and possible solutions

\newpage

\appendix

# Appendix {#sec-appendix}

\newpage

# References
